FROM registry.access.redhat.com/ubi9/python-39:latest 
USER root
WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/
USER 1001
EXPOSE 8001
CMD ["uvicorn", "profiling:app", "--host", "0.0.0.0", "--port", "8001"]